server:
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  session:
    store-type: redis
    timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.70.69.159:3306/oj
    username: root
    password: root
  # Redis 配置
  redis:
    database: 1
    host: 124.70.69.159
    port: 6379
    timeout: 5000
    password:
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 代码沙箱配置
codesandbox:
  type: remote # example：示例，remote：远程，thirdParty：第三方
  host: 124.70.69.159
  port: 8090